#pragma once

#include <map>
#include <string>
#include <vector>
#include <SDL.h>

class Sprite;
class Graph;

/**
 * BmNumFont class
 *
 * BitMap Number Font - A bitmap containing a series of numbers, from 0 to 9, in this order.
 * Offsets are the X positions of each number (i.e., where they begin).
 */
class BmNumFont
{
private:
    Sprite* sprite;
    int offsets[10];
    int numChars;

public:
    BmNumFont() : sprite(nullptr), numChars(0) {
        for (int& offset : offsets) offset = 0;
    }

    void init(Sprite* sprite);
    SDL_Rect getRect(char numChar) const;
    void setValue(int number, int xOff);
    void setValues(const int* xOff);

    Sprite* getSprite() const { return sprite; }
};

/**
 * BMFontChar struct
 *
 * Stores information for an individual BMFont character according to the .fnt format.
 */
struct BMFontChar
{
    int id;           // Character ID
    int x;            // X position in texture
    int y;            // Y position in texture
    int width;        // Width of character in texture
    int height;       // Height of character in texture
    int xoffset;      // X offset when drawing
    int yoffset;      // Y offset when drawing
    int xadvance;     // How much to advance after drawing this character
    int page;         // Texture page (for multi-page fonts)
};

/**
 * BMFontLoader class
 *
 * Loads .fnt files generated by BMFont and stores character and texture page information.
 */
class BMFontLoader
{
private:
    std::map<int, BMFontChar> characters;
    std::string fontTexture;
    int lineHeight;
    int base;
    int scaleW;
    int scaleH;
    int pages;

    bool parseLine(const std::string& line);

public:
    BMFontLoader();
    bool load(const char* fntFilePath);
    const BMFontChar* getChar(int charId) const;

    int getLineHeight() const { return lineHeight; }
    const std::string& getFontTexture() const { return fontTexture; }
};

/**
 * BMFontRenderer class
 *
 * Renders text using the information loaded by BMFontLoader.
 */
class BMFontRenderer
{
private:
    BMFontLoader* font;
    Sprite* fontTexture;
    Graph* graph;
    
    // Text color (R, G, B, A)
    unsigned char colorR, colorG, colorB, colorA;
    
    // Text scale
    float scale;

public:
    BMFontRenderer();
    void init(Graph* gr, BMFontLoader* bmFont, Sprite* texture);
    void setColor(unsigned char r, unsigned char g, unsigned char b, unsigned char a = 255);
    void setScale(float s);
    void text(const char* texto, int x, int y);
    int getTextWidth(const char* texto) const;
    int getTextHeight() const;
    void release();

    // Getters
    BMFontLoader* getFont() const { return font; }
    Sprite* getFontTexture() const { return fontTexture; }
};